### PR TITLE
Features/certificates

### PR DESCRIPTION
**Pull request by parejajd**

### CODE REVIEW

**Review by parejajd — COMMENTED** [review]
This PR is a team work from @BryanHerrera04 @Rohiri @Jorgecuenca1 @parejajd @jaev-977

**Comment by parejajd** [comment]
This PR is a team work from @BryanHerrera04 @Rohiri @Jorgecuenca1 @parejajd @jaev-977

**Comment by andreaveca** [comment]
Hi @parejajd, I want to confirm about the signatures,
I'm doing a test locally, I added a "funcionario" with a own signature but when I see the certificate letter this display the static signature

image

image


Could you please confirm if this part is ok (maybe I'm doing something wrong?) or should be updated?

**Comment by parejajd** [comment]
Hi @andreaveca.

The last commit add the signature to carnet and certificate

Thanks

**Comment by andreaveca** [comment]
Hi @parejajd,

Sorry for my late response. Now I have this issue.
 I can see that you reference in this way **src="/media/{{capacity.medicalcertificate.doctor.official.url}}"** in the admin site where can I added the image?

image

**Comment by BryanHerrera04** [comment]
Hello @andreaveca 

You find it in Official

image
image


I remain pending

**Comment by andreaveca** [comment]
Excellent work! 👍🏻

**Pull request merged**
